--SELECT * FROM ORCHESTRA_GROUP;

SELECT * FROM USERS;
--SELECT * FROM RENTAL;
--SELECT * FROM PARENT;
--SELECT * FROM REHEARSAL;
--SELECT * FROM ORCHESTRA_MEMBER;
--SELECT * FROM ORCHESTRA_GROUP;

--DELETE FROM USERS WHERE username = 'calebsong@gmail.com';


