-- Write a query to display the brand ID, brand name, brand type, and average
-- price of products for the brand that has the largest average product price.
-- (Problem 7.63)

--Doesn't work, don't know how round works


--SELECT MAX (AVG_PRICE) AS AVGPRICE
--FROM(
--	SELECT LGBRAND.BRAND_ID, BRAND_NAME, BRAND_TYPE, AVG (PROD_PRICE) AS AVG_PRICE
--	FROM LGBRAND INNER JOIN LGPRODUCT ON LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID
--	GROUP BY LGBRAND.BRAND_ID
--)AS subquery;

--SELECT LGPRODUCT.BRAND_ID, BRAND_NAME, BRAND_TYPE, AVG (PROD_PRICE) AS AVG_PRICE
--FROM LGBRAND INNER JOIN LGPRODUCT ON LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID
--HAVING AVG (PROD_PRICE) = (
--	SELECT MAX (AVG (PROD_PRICE)) as AVG_PRICE
--	FROM LGPRODUCT
--);

WITH PRICES AS (
SELECT LGPRODUCT.BRAND_ID, BRAND_NAME, BRAND_TYPE, ROUND (AVG (PROD_PRICE),2) AS AVGPRICE
FROM LGBRAND INNER JOIN LGPRODUCT ON LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID
GROUP BY LGPRODUCT.BRAND_ID, BRAND_NAME, BRAND_TYPE
)
SELECT * FROM PRICES
WHERE AVGPRICE = (
	SELECT MAX (AVGPRICE)
	FROM PRICES
)
